base-domain: ${BASE_DOMAIN:`http://localhost:8080`}
oauth2:
  realm-uri: ${REALM_URI:`https://keycloak.glubo.cz/auth/realms/ufnukanazemle/protocol/openid-connect`}
  jwt-certs-uri: ${oauth2.realm-uri}/certs
  jwt-token-uri: ${oauth2.realm-uri}/token
  jwt-auth-uri: ${oauth2.realm-uri}/auth

micronaut:
  application:
    name: backend
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          jwks:
            keycloak:
              url: ${oauth2.jwt-certs-uri}
    enabled: true
    intercept-url-map:
    - pattern: /swagger/**
      access:
        - isAnonymous()
    - pattern: /swagger-ui/**
      access:
        - isAnonymous()
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
db:
  host: ${MARIA_HOST:`localhost`}
  database: ${MARIA_DATABASE:`ufnukanazemle`}
  username: ${MARIA_USERNAME:ufnukanazemle}
  password: ${MARIA_PASSWORD:menetajneheslo1}
r2dbc:
  datasources:
    default:
      url: r2dbc:mariadb://${db.host}:3306/${db.database}
      username: ${db.username}
      password: ${db.password}
      schema-generate: none
      dialect: MYSQL
      options:
  migrate:
    resources-paths:
      - db/migration/*.sql

endpoints:
  enabled: true
